-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."allowed_emails" add column "match_type" text
--  not null default 'EMAIL';
