-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."data_runs" add column "ambiguity_score" double precision
--  null;
