-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TRIGGER trigger_after_investor_insert_create_action
--   AFTER INSERT
--   ON public.investors
--   FOR EACH ROW
--   EXECUTE PROCEDURE public.after_insert_investor_create_action();
