export const ROUTES = {
  ROOT: '/',
  SIGN_IN: '/sign-in',
  ONBOARDING: '/onboarding',
  HOME: '/home',
  COMPANIES: '/companies',
  INVESTORS: '/investors',
  EVENTS: '/events',
  NEWS: '/news',
  PEOPLE: '/people',
  LISTS: '/lists',
  GROUPS: '/groups',
  NOTES: '/notes',
  NOTIFICATIONS: '/notifications',
  INVITE_A_FRIEND: '/invite-a-friend',
  ACCOUNT: '/account',
  PROFILE: '/profile',
  SUPPORT: '/support',
  PRICING: '/pricing',
  CONTACT: '/contact',
  TEAM: '/team',
  BRAND_ASSETS: '/brand-assets',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  NOT_FOUND: '/404',
};
