-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."data_fields" add column "is_valid_identifier" boolean
--  not null default 'false';
