-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."investors" alter column "start_date" type date USING ("start_date"::text::date);
