version: '3'
services:
  postgres:
    image: postgis/postgis:14-3.3
    command: postgres -c 'max_connections=500'
    restart: always
    environment:
      POSTGRES_USER: 'edgeu'
      POSTGRES_DB: 'edgedb'
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./hasura/bootstrap-dev:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: 'pg_isready -U edgeu -d edgedb'

  graphql-engine:
    image: hasura/graphql-engine:v2.7.0
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://edgeu:@postgres:5432/edgedb
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: devsecret
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "you-should-create-your-own-secret-to-use-for-encryption"}'
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  db_data:
  cache:
    driver: local
