-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."data_raw" add column "is_owner_verified" bool
--  not null default 'false';
