-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."resource_links" add column "created_at" timestamptz
--  not null default now();
