-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE investment_rounds ALTER COLUMN round_date TYPE date USING round_date::date;
