name: 'Hasura Steps'
description: 'Clear and apply Hasura metadata, update data fields'
inputs:

runs:
  using: "composite"
  steps:
    - name: Fetch Terraform hasura admin secret path output
      working-directory: infra/terraform/application
      id: tf-hasura-admin-output
      run: |
        output=$(terraform output -raw hasura_admin_secrete_ssm_path)
        echo "TF_OUT_HASURA_ADMIN_SECRET_SSM_PATH=$output" >> $GITHUB_ENV

    - name: Fetch Terraform hasura endpoint output
      working-directory: infra/terraform/application
      id: tf-hasura-endpoint-output
      run: |
        output=$(terraform output -raw hasura_endpoint)
        echo "TF_OUT_HASURA_ENDPOINT=$output" >> $GITHUB_ENV

    - name: Fetch Hasura admin secrete
      working-directory: infra/terraform/application
      id: hasura-admin-secret
      run: |
        value=$(aws ssm get-parameter --name ${{ env.TF_OUT_HASURA_ADMIN_SECRET_SSM_PATH }} --with-decryption --query 'Parameter.Value' --output text)
        echo "HASURA_ADMIN_SECRET=$value" >> $GITHUB_ENV

    - name: Hasura migrate
      uses: tibotiber/hasura-action@v3.0
      with:
        args: migrate apply --database-name default
      env:
        HASURA_WORKDIR: ./infra/hasura
        HASURA_ENGINE_VERSION: v2.29.1
        HASURA_ENDPOINT: ${{ env.TF_OUT_HASURA_ENDPOINT }}
        HASURA_ADMIN_SECRET: ${{ env.HASURA_ADMIN_SECRET }}

    - name: Hasura clear
      uses: tibotiber/hasura-action@v3.0
      with:
        args: metadata clear
      env:
        HASURA_WORKDIR: ./infra/hasura
        HASURA_ENGINE_VERSION: v2.29.1
        HASURA_ENDPOINT: ${{ env.TF_OUT_HASURA_ENDPOINT }}
        HASURA_ADMIN_SECRET: ${{ env.HASURA_ADMIN_SECRET }}

    - name: Hasura apply
      uses: tibotiber/hasura-action@v3.0
      with:
        args: metadata apply
      env:
        HASURA_WORKDIR: ./infra/hasura
        HASURA_ENGINE_VERSION: v2.29.1
        HASURA_ENDPOINT: ${{ env.TF_OUT_HASURA_ENDPOINT }}
        HASURA_ADMIN_SECRET: ${{ env.HASURA_ADMIN_SECRET }}

    - name: Update data fields
      working-directory: ./scripts
      shell: bash
      run: npx ts-node update_data_fields.ts
