-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."people" add column "enrichment_priority" integer
--  not null default '0';
