-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE public.application_meta SET "key" = 'sync_web3_companies' WHERE "key" = 'sync_companies';
-- UPDATE public.application_meta SET "key" = 'sync_web3_vc_firms' WHERE "key" = 'sync_vc_firms';
-- UPDATE public.application_meta SET "key" = 'sync_web3_people' WHERE "key" = 'sync_people';
-- UPDATE public.application_meta SET "key" = 'sync_web3_events' WHERE "key" = 'sync_events';
