-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.companies ALTER COLUMN library TYPE jsonb USING jsonb_build_array(library)::jsonb;
