-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."companies" add column "num_of_views" integer
--  null;
-- alter table "public"."vc_firms" add column "num_of_views" integer
--  null;
-- alter table "public"."events" add column "num_of_views" integer
--  null;
-- alter table "public"."news" add column "num_of_views" integer
--  null;