import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ElemHeading } from "../components/ElemHeading";
import { runGraphQl } from "../utils";

type Props = {
	people: Record<string, any>[];
};

const People: NextPage<Props> = (props) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<ElemHeading title="People" />

				<div className="bg-gray-50 rounded-t-8xl relative z-50">
					<div
						className="
          max-w-6xl
          mx-auto
          min-h-screen
          py-12
          px-4
          sm:px-6
          lg:py-16 lg:px-8
        "
					>
						<div className="flex">
							<div className="block hover:text-primary-500 cursor-pointer">
								Prev
							</div>

							<div className="block hover:text-primary-500 cursor-pointer">
								Next
							</div>
						</div>

						<ul>
							{props.people.map((person) => (
								<li key={person.id} className="hover:text-primary-500">
									<Link href={`/people/${person.slug}`} passHref>
										{person.name}
									</Link>
								</li>
							))}
						</ul>
					</div>
				</div>
			</div>
		</div>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const { data: people } = await runGraphQl(`{ 
    people( 
      _order_by: {name: "asc"},
      _filter: {slug: {_ne: ""}},
    ){ 
        id, 
        name, 
        slug, 
        picture, 
        type
      }
    }`);

	return {
		props: {
			people: people.people,
		},
	};
};

export default People;
