import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ElemButton } from "../components/ElemButton";
import { ElemHeading } from "../components/ElemHeading";
import { ElemPhoto } from "../components/ElemPhoto";
import { runGraphQl } from "../utils";

type Props = {
	vcFirms: Record<string, any>[];
};

const VCFirms: NextPage<Props> = (props) => {
	return (
		<div>
			<Head>
				<title>VC Firms - EdgeIn.io</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<ElemHeading
					title="VC Firms"
					subtitle="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
				>
					<ElemButton href="/" btn="dark" arrow>
						Submit VC Firm
					</ElemButton>
				</ElemHeading>

				<div className="bg-gray-50 rounded-t-8xl relative z-10">
					<div className="max-w-6xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 ">
						<div className="w-full flex flex-col md:grid sm:grid-cols-2 md:grid-cols-3 gap-5 ">
							{props.vcFirms.map((vcfirm) => (
								<Link key={vcfirm.id} href={`/vcfirms/${vcfirm.slug}`}>
									<a className="bg-white rounded-lg overflow-hidden cursor-pointer p-7 md:p-7 flex flex-col justify-between md:h-full mx-auto w-full max-w-md group transition duration-300 ease-in-out transform hover:scale-102 hover:shadow-lg focus:ring focus:ring-primary-300 ">
										<div className="flex items-center w-full">
											<ElemPhoto
												photos={vcfirm.logo}
												wrapClass="flex items-center justify-center shrink-0 w-16 h-16 p-2 bg-white rounded-lg shadow-md"
												imgClass="object-fit max-w-full max-h-full"
												imgAlt={vcfirm.title}
											/>
											<div className="pl-3">
												<h3 className="text-2xl font-bold text-dark-700 break-words min-w-0 sm:text-lg lg:text-xl group-hover:opacity-60 ">
													{vcfirm.vcFirm}
												</h3>
											</div>
										</div>
									</a>
								</Link>
							))}
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const { data: vcFirms } = await runGraphQl(
		"{ vcFirms { id, vcFirm, slug, logo}}"
	);

	return {
		props: {
			vcFirms: vcFirms.vcFirms,
		},
	};
};

export default VCFirms;
