-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."users" add column "additional_emails" jsonb
--  not null default jsonb_build_array();
