CREATE TABLE public.company_errors (
	slug text NULL,
	layer text NULL,
	layer_detail text NULL,
	coin_id int4 NULL,
	"name" text NULL,
	logo jsonb NULL,
	total_employees numeric NULL,
	github text NULL,
	notes text NULL,
	overview text NULL,
	website text NULL,
	careers_page text NULL,
	company_linkedin text NULL,
	year_founded text NULL,
	investor_amount int8 NULL,
	total_valuation text NULL,
	white_paper text NULL,
	market_verified text NULL,
	velocity_linkedin text NULL,
	velocity_token text NULL,
	id serial4 NOT NULL,
	date_added date NULL,
	ico_start date NULL,
	ico_end date NULL,
	audit_file text NULL,
	tags jsonb NULL,
	sentiment jsonb NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	aliases text NULL,
	twitter text NULL,
	discord text NULL,
	glassdoor text NULL,
	"location" text NULL,
	bitcointalk text NULL,
	facebook text NULL,
	instagram text NULL,
	medium text NULL,
	reddit text NULL,
	telegram text NULL,
	youtube text NULL,
	blockchain_explorer text NULL
);
