-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."team_members" add column "enrichment_priority" integer
--  not null default '0';
