-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."organization_edit_access" add column "resource_type" text
--  not null;
