-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_group_invites" add column "created_by_user_id" integer
--  null;
