-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."status_type_enum_group_2"("value", "description") VALUES (E'published', E'used for status fields published/draft');
-- INSERT INTO "public"."status_type_enum_group_2"("value", "description") VALUES (E'draft', E'used for status fields published/draft');
