-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."investors" alter column "end_date" type date USING ("end_date"::text::date);
