table:
  name: vc_firms
  schema: public
array_relationships:
  - name: follows
    using:
      manual_configuration:
        column_mapping:
          id: resource_id
        insertion_order: null
        remote_table:
          name: follows_vc_firms
          schema: public
  - name: from_links
    using:
      manual_configuration:
        column_mapping:
          id: from_vc_firm_id
        insertion_order: null
        remote_table:
          name: resource_links
          schema: public
  - name: investments
    using:
      foreign_key_constraint_on:
        column: vc_firm_id
        table:
          name: investments
          schema: public
  - name: investors
    using:
      foreign_key_constraint_on:
        column: vc_firm_id
        table:
          name: investors
          schema: public
  - name: news_links
    using:
      manual_configuration:
        column_mapping:
          id: vc_firm_id
        insertion_order: null
        remote_table:
          name: news_organizations
          schema: public
  - name: to_links
    using:
      manual_configuration:
        column_mapping:
          id: to_vc_firm_id
        insertion_order: null
        remote_table:
          name: resource_links
          schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - logo
        - external_id
        - linkedin
        - name
        - slug
        - website
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - created_at
        - geopoint
        - github
        - glassdoor
        - id
        - investment_amount_total
        - latest_investment
        - library
        - linkedin
        - location
        - location_json
        - logo
        - name
        - num_of_exits
        - num_of_investments
        - overview
        - sentiment
        - slug
        - status_tags
        - tags
        - team_size
        - telegram
        - twitter
        - updated_at
        - web3_address
        - website
        - year_founded
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - external_id
        - github
        - glassdoor
        - id
        - linkedin
        - logo
        - name
        - slug
        - telegram
        - twitter
        - web3_address
        - website
      filter: {}
  - role: viewer
    permission:
      columns:
        - created_at
        - datapoints_count
        - discord
        - geopoint
        - github
        - glassdoor
        - id
        - investment_amount_total
        - latest_investment
        - library
        - linkedin
        - location
        - location_json
        - logo
        - name
        - num_of_exits
        - num_of_investments
        - num_of_views
        - overview
        - sentiment
        - slug
        - status
        - status_tags
        - tags
        - team_size
        - telegram
        - twitter
        - updated_at
        - web3_address
        - website
        - year_founded
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
