table:
  schema: public
  name: follows
object_relationships:
  - name: list
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: lists
        insertion_order: null
        column_mapping:
          list_id: id
