table:
  schema: public
  name: companies
object_relationships:
  - name: coin
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: coins
        insertion_order: null
        column_mapping:
          coin_id: id
array_relationships:
  - name: investment_rounds
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          schema: public
          name: investment_rounds
  - name: teamMembers
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          schema: public
          name: team_members
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - logo
        - total_employees
        - careers_page
        - coin_id
        - company_linkedin
        - external_id
        - github
        - investor_amount
        - layer
        - layer_detail
        - market_verified
        - name
        - notes
        - overview
        - slug
        - total_valuation
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - logo
        - total_employees
        - careers_page
        - coin_id
        - company_linkedin
        - external_id
        - github
        - investor_amount
        - layer
        - layer_detail
        - market_verified
        - name
        - notes
        - overview
        - slug
        - total_valuation
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
      filter: {}
      limit: 50
update_permissions:
  - role: user
    permission:
      columns:
        - careers_page
        - coin_id
        - company_linkedin
        - external_id
        - github
        - id
        - investor_amount
        - layer
        - layer_detail
        - logo
        - market_verified
        - name
        - notes
        - overview
        - slug
        - total_employees
        - total_valuation
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
      filter: {}
      check: {}
