table:
  schema: public
  name: user_group_invites
object_relationships:
  - name: users
    using:
      foreign_key_constraint_on: user_group_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - user_group_id
        - email
        - created_at
      filter:
        users:
          user_group_members:
            user_id:
              _eq: X-Hasura-User-Id
      limit: 50
      allow_aggregations: true
