table:
  schema: public
  name: vc_firms_edit_access
object_relationships:
  - name: vc_firm
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: vc_firms
        insertion_order: null
        column_mapping:
          resource_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - resource_id
        - user_id
        - resource_type
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      limit: 50
      allow_aggregations: true
