table:
  name: lists
  schema: public
object_relationships:
  - name: created_by
    using:
      manual_configuration:
        column_mapping:
          created_by_id: id
        insertion_order: null
        remote_table:
          name: users_public
          schema: public
array_relationships:
  - name: follows_companies
    using:
      manual_configuration:
        column_mapping:
          id: list_id
        insertion_order: null
        remote_table:
          name: follows_companies
          schema: public
  - name: follows_people
    using:
      manual_configuration:
        column_mapping:
          id: list_id
        insertion_order: null
        remote_table:
          name: follows_people
          schema: public
  - name: follows_vcfirms
    using:
      manual_configuration:
        column_mapping:
          id: list_id
        insertion_order: null
        remote_table:
          name: follows_vc_firms
          schema: public
  - name: list_members
    using:
      foreign_key_constraint_on:
        column: list_id
        table:
          name: list_members
          schema: public
  - name: user_groups
    using:
      manual_configuration:
        column_mapping:
          id: list_id
        insertion_order: null
        remote_table:
          name: list_user_groups
          schema: public
computed_fields:
  - name: total_no_of_resources
    definition:
      function:
        name: lists_total_no_of_companies
        schema: public
    comment: Computed field to get total no. of companies in a list
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_at
        - created_by_id
        - id
        - name
        - public
        - type
        - updated_at
      computed_fields:
        - total_no_of_resources
      filter:
        _or:
          - list_members:
              user_id:
                _eq: X-Hasura-User-Id
          - user_groups:
              user_group:
                user_group_members:
                  user_id:
                    _eq: X-Hasura-User-Id
          - public:
              _eq: true
      limit: 50
      allow_aggregations: true
