table:
  schema: public
  name: companies
object_relationships:
  - name: coin
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: coins
        insertion_order: null
        column_mapping:
          coin_id: id
array_relationships:
  - name: follows
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_companies
        insertion_order: null
        column_mapping:
          id: resource_id
  - name: investment_rounds
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          schema: public
          name: investment_rounds
  - name: teamMembers
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          schema: public
          name: team_members
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - logo
        - total_employees
        - careers_page
        - coin_id
        - company_linkedin
        - external_id
        - github
        - investor_amount
        - layer
        - layer_detail
        - market_verified
        - name
        - notes
        - overview
        - slug
        - total_valuation
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - audit_file
        - careers_page
        - coin_id
        - company_linkedin
        - date_added
        - external_id
        - github
        - ico_end
        - ico_start
        - id
        - investor_amount
        - layer
        - layer_detail
        - logo
        - market_verified
        - name
        - notes
        - overview
        - slug
        - tags
        - total_employees
        - total_valuation
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
      filter: {}
      limit: 50
  - role: viewer
    permission:
      columns:
        - investor_amount
        - date_added
        - ico_end
        - ico_start
        - coin_id
        - id
        - location_json
        - logo
        - sentiment
        - status_tags
        - tags
        - total_employees
        - aliases
        - audit_file
        - bitcointalk
        - blockchain_explorer
        - careers_page
        - company_linkedin
        - discord
        - external_id
        - facebook
        - github
        - glassdoor
        - instagram
        - layer
        - layer_detail
        - location
        - market_verified
        - medium
        - name
        - notes
        - overview
        - reddit
        - slug
        - status
        - telegram
        - total_valuation
        - twitter
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
        - youtube
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
