table:
  name: follows
  schema: public
object_relationships:
  - name: follow_member
    using:
      manual_configuration:
        column_mapping:
          list_id: list_id
        insertion_order: null
        remote_table:
          name: list_members
          schema: public
  - name: list
    using:
      manual_configuration:
        column_mapping:
          list_id: id
        insertion_order: null
        remote_table:
          name: lists
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by_user_id
        - id
        - list_id
        - resource_id
        - resource_type
      filter:
        follow_member:
          user_id:
            _eq: X-Hasura-User-Id
      limit: 50
