table:
  schema: public
  name: user_group_invites
object_relationships:
  - name: created_by
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          created_by_user_id: id
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_at
        - created_by_user_id
        - email
        - id
        - user_group_id
      filter:
        user_group:
          user_group_members:
            user_id:
              _eq: X-Hasura-User-Id
      limit: 50
