table:
  schema: public
  name: users_public
object_relationships:
  - name: person
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: people
        insertion_order: null
        column_mapping:
          person_id: id
array_relationships:
  - name: list_members
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: list_members
        insertion_order: null
        column_mapping:
          id: user_id
  - name: user_group_members
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: user_group_members
        insertion_order: null
        column_mapping:
          id: user_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - display_name
        - email
        - person_id
      filter: {}
