table:
  name: team_members
  schema: public
object_relationships:
  - name: company
    using:
      foreign_key_constraint_on: company_id
  - name: person
    using:
      foreign_key_constraint_on: person_id
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - founder
        - end_date
        - start_date
        - company_id
        - id
        - person_id
        - external_id
        - function
        - seniority
        - title
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - founder
        - end_date
        - start_date
        - company_id
        - id
        - person_id
        - external_id
        - function
        - seniority
        - title
      filter:
        person:
          status:
            _eq: published
      limit: 50
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - founder
        - end_date
        - start_date
        - company_id
        - id
        - person_id
        - external_id
        - function
        - seniority
        - title
      filter: {}
  - role: viewer
    permission:
      columns:
        - company_id
        - email_address
        - end_date
        - external_id
        - founder
        - function
        - id
        - person_id
        - seniority
        - start_date
        - title
      filter:
        person:
          status:
            _eq: published
      limit: 50
      allow_aggregations: true
