table:
  schema: public
  name: user_group_invites
object_relationships:
  - name: created_by
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          created_by_user_id: id
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
