table:
  schema: public
  name: investments
object_relationships:
  - name: investment_round
    using:
      foreign_key_constraint_on: round_id
  - name: person
    using:
      foreign_key_constraint_on: person_id
  - name: vc_firm
    using:
      foreign_key_constraint_on: vc_firm_id
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - round_id
        - person_id
        - vc_firm_id
        - id
        - external_id
      backend_only: false
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - amount
        - id
        - person_id
        - round_id
        - vc_firm_id
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - id
        - person_id
        - round_id
        - vc_firm_id
        - external_id
      filter: {}
  - role: viewer
    permission:
      columns:
        - amount
        - id
        - person_id
        - round_id
        - vc_firm_id
      filter:
        status:
          _eq: published
      limit: 250
