table:
  name: follows_people
  schema: public
object_relationships:
  - name: person
    using:
      manual_configuration:
        column_mapping:
          resource_id: id
        insertion_order: null
        remote_table:
          name: people
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by_user_id
        - resource_id
        - id
        - resource_type
        - list_id
      filter: {}
      limit: 50
      allow_aggregations: true
