table:
  name: user_group_members
  schema: public
object_relationships:
  - name: user
    using:
      manual_configuration:
        column_mapping:
          user_id: id
        insertion_order: null
        remote_table:
          name: users_public
          schema: public
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - user_group_id
        - user_id
      filter:
        _or:
          - user_group:
              public:
                _eq: true
          - user_group:
              user_group_members:
                user_id:
                  _eq: X-Hasura-User-Id
      limit: 50
