table:
  name: investment_rounds
  schema: public
object_relationships:
  - name: company
    using:
      foreign_key_constraint_on: company_id
array_relationships:
  - name: investments
    using:
      foreign_key_constraint_on:
        column: round_id
        table:
          name: investments
          schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - company_id
        - id
        - amount
        - valuation
        - external_id
        - round
        - round_date
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - amount
        - company_id
        - currency
        - id
        - round
        - round_date
        - valuation
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - company_id
        - id
        - amount
        - valuation
        - external_id
        - round
        - round_date
      filter: {}
  - role: viewer
    permission:
      columns:
        - amount
        - company_id
        - currency
        - id
        - round
        - round_date
        - valuation
      filter:
        status:
          _eq: published
      limit: 250
      allow_aggregations: true
