table:
  schema: public
  name: follows
object_relationships:
  - name: list
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: lists
        insertion_order: null
        column_mapping:
          list_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by_user_id
        - id
        - list_id
        - resource_id
        - resource_type
      filter:
        created_by_user_id:
          _eq: X-Hasura-User-Id
      allow_aggregations: true
