table:
  schema: public
  name: people
array_relationships:
  - name: investments
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          schema: public
          name: investments
  - name: investors
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          schema: public
          name: investors
  - name: team_members
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          schema: public
          name: team_members
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - picture
        - external_id
        - github
        - linkedin
        - name
        - personal_email
        - slug
        - type
        - work_email
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - picture
        - external_id
        - github
        - linkedin
        - name
        - personal_email
        - slug
        - type
        - work_email
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - id
        - picture
        - external_id
        - github
        - linkedin
        - name
        - personal_email
        - slug
        - type
        - work_email
      filter: {}
      check: {}
