table:
  schema: public
  name: blockchains
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - name
      filter: {}
  - role: viewer
    permission:
      columns:
        - id
        - name
      filter: {}
      allow_aggregations: true
