table:
  name: comments
  schema: public
object_relationships:
  - name: created_by_user
    using:
      manual_configuration:
        column_mapping:
          created_by_user_id: id
        insertion_order: null
        remote_table:
          name: users_public
          schema: public
  - name: note
    using:
      manual_configuration:
        column_mapping:
          note_id: id
        insertion_order: null
        remote_table:
          name: notes
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by_user_id
        - id
        - note_id
        - content
        - created_at
      filter: {}
