table:
  schema: public
  name: investors
object_relationships:
  - name: person
    using:
      foreign_key_constraint_on: person_id
  - name: vc_firm
    using:
      foreign_key_constraint_on: vc_firm_id
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - vc_firm_id
        - person_id
        - function
        - start_date
        - end_date
        - seniority
        - title
        - id
        - external_id
      backend_only: false
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - id
        - person_id
        - vc_firm_id
        - end_date
        - start_date
        - external_id
        - function
        - seniority
        - title
        - created_at
        - updated_at
      filter:
        person:
          status:
            _eq: published
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - id
        - person_id
        - vc_firm_id
        - end_date
        - start_date
        - external_id
        - function
        - seniority
        - title
      filter: {}
  - role: viewer
    permission:
      columns:
        - id
        - person_id
        - vc_firm_id
        - end_date
        - start_date
        - external_id
        - function
        - seniority
        - title
        - created_at
        - updated_at
      filter:
        person:
          status:
            _eq: published
      allow_aggregations: true
