table:
  schema: public
  name: coins
object_relationships:
  - name: blockchain
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: blockchains
        insertion_order: null
        column_mapping:
          blockchain_id: id
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - blockchain_id
        - external_id
        - id
        - name
        - ticker
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - blockchain_id
        - company_id
        - id
        - name
        - ticker
        - type
      filter: {}
      limit: 50
  - role: user
    permission:
      columns:
        - blockchain_id
        - id
        - external_id
        - name
        - ticker
      filter: {}
  - role: viewer
    permission:
      columns:
        - blockchain_id
        - company_id
        - id
        - name
        - ticker
        - type
      filter: {}
      limit: 50
      allow_aggregations: true
