table:
  schema: public
  name: users
object_relationships:
  - name: person
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: people
        insertion_order: null
        column_mapping:
          person_id: id
array_relationships:
  - name: list_members
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          schema: public
          name: list_members
