table:
  schema: public
  name: vc_firms_edit_access
object_relationships:
  - name: vc_firm
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: vc_firms
        insertion_order: null
        column_mapping:
          resource_id: id
