table:
  schema: public
  name: companies_edit_access
object_relationships:
  - name: company
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: companies
        insertion_order: null
        column_mapping:
          resource_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - resource_id
        - user_id
        - resource_type
      filter: {}
      allow_aggregations: true
