table:
  schema: public
  name: companies
array_relationships:
  - name: investment_rounds
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          schema: public
          name: investment_rounds
  - name: teamMembers
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          schema: public
          name: team_members
