table:
  name: event_person
  schema: public
object_relationships:
  - name: event
    using:
      manual_configuration:
        column_mapping:
          event_id: id
        insertion_order: null
        remote_table:
          name: events
          schema: public
  - name: person
    using:
      manual_configuration:
        column_mapping:
          person_id: id
        insertion_order: null
        remote_table:
          name: people
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - event_id
        - id
        - person_id
        - type
        - created_at
      filter: {}
