table:
  name: news_organizations
  schema: public
object_relationships:
  - name: company
    using:
      manual_configuration:
        column_mapping:
          company_id: id
        insertion_order: null
        remote_table:
          name: companies
          schema: public
  - name: news
    using:
      manual_configuration:
        column_mapping:
          news_id: id
        insertion_order: null
        remote_table:
          name: news
          schema: public
  - name: vc_firm
    using:
      manual_configuration:
        column_mapping:
          vc_firm_id: id
        insertion_order: null
        remote_table:
          name: vc_firms
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - company_id
        - created_at
        - id
        - type
        - news_id
        - updated_at
        - vc_firm_id
      filter: {}
      limit: 50
