table:
  name: resource_edit_access
  schema: public
object_relationships:
  - name: company
    using:
      manual_configuration:
        column_mapping:
          resource_id: id
        insertion_order: null
        remote_table:
          name: companies
          schema: public
  - name: vc_firm
    using:
      manual_configuration:
        column_mapping:
          resource_id: id
        insertion_order: null
        remote_table:
          name: vc_firms
          schema: public
