table:
  schema: public
  name: follows_people
object_relationships:
  - name: person
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: people
        insertion_order: null
        column_mapping:
          resource_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by_user_id
        - resource_id
        - id
        - resource_type
        - list_id
      filter: {}
      limit: 200
