table:
  schema: public
  name: reset_passwords
object_relationships:
  - name: created_by_user
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          created_by_user_id: id
  - name: user
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          user_id: id
