table:
  schema: public
  name: lists
array_relationships:
  - name: follows_companies
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_companies
        insertion_order: null
        column_mapping:
          id: list_id
  - name: follows_vcfirms
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_vc_firms
        insertion_order: null
        column_mapping:
          id: list_id
computed_fields:
  - name: total_no_of_resources
    definition:
      function:
        schema: public
        name: lists_total_no_of_companies
    comment: Computed field to get total no. of companies in a list
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by_id
        - id
        - name
      computed_fields:
        - total_no_of_resources
      filter: {}
      allow_aggregations: true
