table:
  name: reset_passwords
  schema: public
object_relationships:
  - name: created_by_user
    using:
      manual_configuration:
        column_mapping:
          created_by_user_id: id
        insertion_order: null
        remote_table:
          name: users
          schema: public
  - name: user
    using:
      manual_configuration:
        column_mapping:
          user_id: id
        insertion_order: null
        remote_table:
          name: users
          schema: public
