table:
  schema: public
  name: list_members
object_relationships:
  - name: list
    using:
      foreign_key_constraint_on: list_id
  - name: user
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          user_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - list_id
        - user_id
        - member_type
      filter: {}
      limit: 50
