table:
  name: news_person
  schema: public
object_relationships:
  - name: news
    using:
      manual_configuration:
        column_mapping:
          news_id: id
        insertion_order: null
        remote_table:
          name: news
          schema: public
  - name: people
    using:
      manual_configuration:
        column_mapping:
          person_id: id
        insertion_order: null
        remote_table:
          name: people
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - type
        - id
        - news_id
        - person_id
        - created_at
        - updated_at
      filter: {}
      limit: 50
