table:
  schema: public
  name: events
object_relationships:
  - name: parent_event
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: events
        insertion_order: null
        column_mapping:
          parent_event_id: id
array_relationships:
  - name: event_organization
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: event_organization
        insertion_order: null
        column_mapping:
          id: event_id
  - name: event_person
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: event_person
        insertion_order: null
        column_mapping:
          id: event_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - end_date
        - start_date
        - id
        - parent_event_id
        - location_json
        - link
        - name
        - notes
        - size
        - status
        - created_at
        - updated_at
      filter:
        status:
          _eq: published
      limit: 50
