table:
  schema: public
  name: lists
array_relationships:
  - name: follows_companies
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_companies
        insertion_order: null
        column_mapping:
          id: list_id
