table:
  schema: public
  name: list_user_groups
object_relationships:
  - name: list
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: lists
        insertion_order: null
        column_mapping:
          list_id: id
  - name: user_group
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: user_groups
        insertion_order: null
        column_mapping:
          user_group_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - list_id
        - user_group_id
      filter: {}
      limit: 50
      allow_aggregations: true
