table:
  name: people
  schema: public
object_relationships:
  - name: people_computed_data
    using:
      manual_configuration:
        column_mapping:
          id: person_id
        insertion_order: null
        remote_table:
          name: people_computed_data
          schema: public
  - name: user
    using:
      manual_configuration:
        column_mapping:
          id: person_id
        insertion_order: null
        remote_table:
          name: users_public
          schema: public
array_relationships:
  - name: follows
    using:
      manual_configuration:
        column_mapping:
          id: resource_id
        insertion_order: null
        remote_table:
          name: follows_people
          schema: public
  - name: investments
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          name: investments
          schema: public
  - name: investors
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          name: investors
          schema: public
  - name: news_links
    using:
      manual_configuration:
        column_mapping:
          id: person_id
        insertion_order: null
        remote_table:
          name: news_person
          schema: public
  - name: team_members
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          name: team_members
          schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - picture
        - about
        - city
        - country
        - external_id
        - facebook_url
        - github
        - linkedin
        - name
        - personal_email
        - slug
        - status
        - twitter_url
        - type
        - website_url
        - work_email
        - created_at
        - updated_at
        - email

select_permissions:
  - role: api_viewer
    permission:
      columns:
        - about
        - city
        - country
        - created_at
        - discord
        - email
        - facebook_url
        - geopoint
        - github
        - id
        - library
        - linkedin
        - location_json
        - name
        - personal_email
        - picture
        - slug
        - telegram
        - twitter_url
        - type
        - updated_at
        - web3_address
        - website_url
        - work_email
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - about
        - city
        - country
        - created_at
        - discord
        - email
        - external_id
        - facebook_url
        - geopoint
        - github
        - id
        - linkedin
        - location_json
        - name
        - personal_email
        - picture
        - slug
        - telegram
        - twitter_url
        - type
        - updated_at
        - web3_address
        - website_url
        - work_email
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
  - role: viewer
    permission:
      columns:
        - about
        - city
        - country
        - created_at
        - datapoints_count
        - discord
        - email
        - facebook_url
        - geopoint
        - github
        - id
        - library
        - linkedin
        - location_json
        - name
        - personal_email
        - picture
        - slug
        - status
        - telegram
        - twitter_url
        - type
        - updated_at
        - web3_address
        - website_url
        - work_email
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
