table:
  name: notes
  schema: public
object_relationships:
  - name: created_by_user
    using:
      manual_configuration:
        column_mapping:
          created_by: id
        insertion_order: null
        remote_table:
          name: users_public
          schema: public
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
array_relationships:
  - name: comments
    using:
      manual_configuration:
        column_mapping:
          id: note_id
        insertion_order: null
        remote_table:
          name: comments
          schema: public
  - name: likes
    using:
      manual_configuration:
        column_mapping:
          id: note_id
        insertion_order: null
        remote_table:
          name: likes
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - audience
        - created_at
        - created_by
        - id
        - notes
        - resource_id
        - resource_type
        - updated_at
        - user_group_id
      filter: {}
      limit: 50
