table:
  name: list_user_groups
  schema: public
object_relationships:
  - name: list
    using:
      manual_configuration:
        column_mapping:
          list_id: id
        insertion_order: null
        remote_table:
          name: lists
          schema: public
  - name: user_group
    using:
      manual_configuration:
        column_mapping:
          user_group_id: id
        insertion_order: null
        remote_table:
          name: user_groups
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - list_id
        - user_group_id
      filter:
        _or:
          - user_group:
              user_group_members:
                user_id:
                  _eq: X-Hasura-User-Id
          - user_group:
              public:
                _eq: true
      limit: 50
