table:
  name: resource_links
  schema: public
object_relationships:
  - name: from_company
    using:
      manual_configuration:
        column_mapping:
          from_company_id: id
        insertion_order: null
        remote_table:
          name: companies
          schema: public
  - name: from_vc_firm
    using:
      manual_configuration:
        column_mapping:
          from_vc_firm_id: id
        insertion_order: null
        remote_table:
          name: vc_firms
          schema: public
  - name: to_company
    using:
      manual_configuration:
        column_mapping:
          to_company_id: id
        insertion_order: null
        remote_table:
          name: companies
          schema: public
  - name: to_vc_firm
    using:
      manual_configuration:
        column_mapping:
          to_vc_firm_id: id
        insertion_order: null
        remote_table:
          name: vc_firms
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - from_company_id
        - from_vc_firm_id
        - to_company_id
        - to_vc_firm_id
        - link_type
        - id
      filter: {}
      limit: 50
