table:
  schema: public
  name: notifications
object_relationships:
  - name: company
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: companies
        insertion_order: null
        column_mapping:
          company_id: id
  - name: vc_firm
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: vc_firms
        insertion_order: null
        column_mapping:
          vc_firm_id: id
array_relationships:
  - name: notification_actions
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: notification_actions
        insertion_order: null
        column_mapping:
          id: notification_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - read
        - company_id
        - id
        - target_user_id
        - vc_firm_id
        - action_ids
        - event_type
        - follow_resource_type
        - message
        - notification_resource_type
        - created_at
        - read_at
        - updated_at
      filter: {}
      allow_aggregations: true
