table:
  schema: public
  name: billing_org
select_permissions:
  - role: viewer
    permission:
      columns:
        - customer_id
        - id
        - plan
        - status
        - user_limit
      filter:
        id:
          _eq: X-Hasura-User-Id
      allow_aggregations: true
