table:
  name: users_public
  schema: public
object_relationships:
  - name: person
    using:
      manual_configuration:
        column_mapping:
          person_id: id
        insertion_order: null
        remote_table:
          name: people
          schema: public
array_relationships:
  - name: list_members
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: list_members
          schema: public
  - name: user_group_members
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: user_group_members
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - display_name
        - email
        - person_id
      filter:
        _or:
          - user_group_members:
              user_group:
                public:
                  _eq: true
          - user_group_members:
              user_group:
                user_group_members:
                  user_id:
                    _eq: X-Hasura-User-Id
          - list_members:
              list:
                public:
                  _eq: true
          - list_members:
              list:
                list_members:
                  user_id:
                    _eq: X-Hasura-User-Id
