table:
  name: notification_actions
  schema: public
object_relationships:
  - name: action
    using:
      manual_configuration:
        column_mapping:
          action_id: id
        insertion_order: null
        remote_table:
          name: actions
          schema: public
  - name: notification
    using:
      manual_configuration:
        column_mapping:
          notification_id: id
        insertion_order: null
        remote_table:
          name: notifications
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - action_id
        - id
        - notification_id
        - created_at
      filter: {}
