table:
  schema: public
  name: team_members
object_relationships:
  - name: company
    using:
      foreign_key_constraint_on: company_id
  - name: person
    using:
      foreign_key_constraint_on: person_id
