table:
  schema: public
  name: users_public
object_relationships:
  - name: person
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: people
        insertion_order: null
        column_mapping:
          person_id: id
array_relationships:
  - name: list_members
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: list_members
        insertion_order: null
        column_mapping:
          id: user_id
  - name: user_group_members
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: user_group_members
        insertion_order: null
        column_mapping:
          id: user_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - display_name
        - email
        - person_id
      filter:
        _or:
          - user_group_members:
              user_group:
                public:
                  _eq: true
          - user_group_members:
              user_group:
                user_group_members:
                  user_id:
                    _eq: X-Hasura-User-Id
          - list_members:
              list:
                public:
                  _eq: true
          - list_members:
              list:
                list_members:
                  user_id:
                    _eq: X-Hasura-User-Id
