table:
  schema: public
  name: investment_rounds
object_relationships:
  - name: company
    using:
      foreign_key_constraint_on: company_id
array_relationships:
  - name: investments
    using:
      foreign_key_constraint_on:
        column: round_id
        table:
          schema: public
          name: investments
