table:
  schema: public
  name: user_group_invites
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - user_group_id
        - email
        - created_at
      filter: {}
      allow_aggregations: true
