table:
  name: users
  schema: public
object_relationships:
  - name: billing_org
    using:
      manual_configuration:
        column_mapping:
          billing_org_id: id
        insertion_order: null
        remote_table:
          name: billing_org
          schema: public
  - name: person
    using:
      manual_configuration:
        column_mapping:
          person_id: id
        insertion_order: null
        remote_table:
          name: people
          schema: public
array_relationships:
  - name: list_members
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: list_members
          schema: public
  - name: organization_companies
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: companies_edit_access
          schema: public
  - name: organization_vc_firms
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: vc_firms_edit_access
          schema: public
computed_fields:
  - name: credits
    definition:
      function:
        name: user_credits
        schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - active
        - additional_emails
        - auth0_linkedin_id
        - auth0_user_pass_id
        - billing_org_id
        - display_name
        - email
        - external_id
        - feature_flags
        - id
        - is_auth0_verified
        - last_transaction_expiration
        - onboarding_information
        - person_id
        - preferences
        - reference_id
        - reference_user_id
        - role
        - use_credits_system
      computed_fields:
        - credits
      filter:
        id:
          _eq: X-Hasura-User-Id
