table:
  schema: public
  name: likes
object_relationships:
  - name: created_by_user
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          created_by_user_id: id
  - name: note
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: notes
        insertion_order: null
        column_mapping:
          note_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by_user_id
        - id
        - note_id
        - created_at
      filter: {}
