table:
  schema: public
  name: lists
array_relationships:
  - name: follows_companies
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_companies
        insertion_order: null
        column_mapping:
          id: list_id
  - name: list_members
    using:
      foreign_key_constraint_on:
        column: list_id
        table:
          schema: public
          name: list_members
computed_fields:
  - name: total_no_of_resources
    definition:
      function:
        schema: public
        name: lists_total_no_of_companies
    comment: Computed field to get total no. of companies in a list
