table:
  schema: public
  name: investors
object_relationships:
  - name: person
    using:
      foreign_key_constraint_on: person_id
  - name: vc_firm
    using:
      foreign_key_constraint_on: vc_firm_id
