table:
  schema: public
  name: event_organization
object_relationships:
  - name: company
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: companies
        insertion_order: null
        column_mapping:
          company_id: id
  - name: event
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: events
        insertion_order: null
        column_mapping:
          event_id: id
  - name: vc_firm
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: vc_firms
        insertion_order: null
        column_mapping:
          vc_firm_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - company_id
        - event_id
        - id
        - vc_firm_id
        - created_at
      filter: {}
