table:
  schema: public
  name: events
object_relationships:
  - name: parent_event
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: events
        insertion_order: null
        column_mapping:
          parent_event_id: id
