table:
  schema: public
  name: people
array_relationships:
  - name: investments
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          schema: public
          name: investments
  - name: investors
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          schema: public
          name: investors
  - name: team_members
    using:
      foreign_key_constraint_on:
        column: person_id
        table:
          schema: public
          name: team_members
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - picture
        - about
        - city
        - country
        - external_id
        - facebook_url
        - github
        - linkedin
        - name
        - personal_email
        - slug
        - status
        - twitter_url
        - type
        - website_url
        - work_email
        - created_at
        - updated_at
        - email
      backend_only: false
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - about
        - city
        - country
        - created_at
        - email
        - facebook_url
        - github
        - id
        - linkedin
        - name
        - personal_email
        - picture
        - slug
        - twitter_url
        - type
        - updated_at
        - website_url
        - work_email
      filter:
        status:
          _eq: published
      limit: 50
  - role: user
    permission:
      columns:
        - about
        - city
        - country
        - created_at
        - email
        - external_id
        - facebook_url
        - github
        - id
        - linkedin
        - name
        - personal_email
        - picture
        - slug
        - twitter_url
        - type
        - updated_at
        - website_url
        - work_email
      filter:
        status:
          _eq: published
  - role: viewer
    permission:
      columns:
        - about
        - city
        - country
        - created_at
        - email
        - facebook_url
        - github
        - id
        - linkedin
        - name
        - personal_email
        - picture
        - slug
        - status
        - twitter_url
        - type
        - updated_at
        - website_url
        - work_email
      filter:
        status:
          _eq: published
      limit: 50
