table:
  schema: public
  name: lists
object_relationships:
  - name: created_by
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          created_by_id: id
array_relationships:
  - name: follows_companies
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_companies
        insertion_order: null
        column_mapping:
          id: list_id
  - name: follows_people
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_people
        insertion_order: null
        column_mapping:
          id: list_id
  - name: follows_vcfirms
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: follows_vc_firms
        insertion_order: null
        column_mapping:
          id: list_id
  - name: list_members
    using:
      foreign_key_constraint_on:
        column: list_id
        table:
          schema: public
          name: list_members
  - name: user_groups
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: list_user_groups
        insertion_order: null
        column_mapping:
          id: list_id
computed_fields:
  - name: total_no_of_resources
    definition:
      function:
        schema: public
        name: lists_total_no_of_companies
    comment: Computed field to get total no. of companies in a list
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_at
        - created_by_id
        - id
        - name
        - type
      computed_fields:
        - total_no_of_resources
      filter:
        _or:
          - list_members:
              user_id:
                _eq: X-Hasura-User-Id
          - user_groups:
              user_group:
                user_group_members:
                  user_id:
                    _eq: X-Hasura-User-Id
      limit: 50
