table:
  schema: public
  name: notes
object_relationships:
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
array_relationships:
  - name: comments
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: comments
        insertion_order: null
        column_mapping:
          id: note_id
  - name: likes
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: likes
        insertion_order: null
        column_mapping:
          id: note_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - audience
        - created_at
        - created_by
        - id
        - notes
        - resource_id
        - resource_type
        - updated_at
        - user_group_id
      filter:
        user_group:
          user_group_members:
            user_id:
              _eq: X-Hasura-User-Id
      limit: 50
