table:
  name: list_members
  schema: public
object_relationships:
  - name: list
    using:
      foreign_key_constraint_on: list_id
  - name: user
    using:
      manual_configuration:
        column_mapping:
          user_id: id
        insertion_order: null
        remote_table:
          name: users_public
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - list_id
        - user_id
        - member_type
      filter: {}
      limit: 50
