table:
  schema: public
  name: user_group_members
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
