table:
  schema: public
  name: users
array_relationships:
  - name: list_members
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          schema: public
          name: list_members
