table:
  schema: public
  name: follows_people
object_relationships:
  - name: person
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: people
        insertion_order: null
        column_mapping:
          resource_id: id
