table:
  name: companies
  schema: public
object_relationships:
  - name: coin
    using:
      manual_configuration:
        column_mapping:
          coin_id: id
        insertion_order: null
        remote_table:
          name: coins
          schema: public
array_relationships:
  - name: follows
    using:
      manual_configuration:
        column_mapping:
          id: resource_id
        insertion_order: null
        remote_table:
          name: follows_companies
          schema: public
  - name: from_links
    using:
      manual_configuration:
        column_mapping:
          id: from_company_id
        insertion_order: null
        remote_table:
          name: resource_links
          schema: public
  - name: investment_rounds
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          name: investment_rounds
          schema: public
  - name: news_links
    using:
      manual_configuration:
        column_mapping:
          id: company_id
        insertion_order: null
        remote_table:
          name: news_organizations
          schema: public
  - name: teamMembers
    using:
      foreign_key_constraint_on:
        column: company_id
        table:
          name: team_members
          schema: public
  - name: to_links
    using:
      manual_configuration:
        column_mapping:
          id: to_company_id
        insertion_order: null
        remote_table:
          name: resource_links
          schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - logo
        - total_employees
        - careers_page
        - coin_id
        - company_linkedin
        - smart_contract
        - external_id
        - github
        - investor_amount
        - layer
        - layer_detail
        - market_verified
        - name
        - notes
        - overview
        - slug
        - total_valuation
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - aliases
        - audit_file
        - bitcointalk
        - blockchain_explorer
        - blockchain_network
        - careers_page
        - coin_id
        - company_linkedin
        - created_at
        - date_added
        - discord
        - facebook
        - geopoint
        - github
        - glassdoor
        - ico_end
        - ico_start
        - id
        - instagram
        - investor_amount
        - layer
        - layer_detail
        - library
        - location
        - location_json
        - logo
        - market_verified
        - medium
        - name
        - notes
        - overview
        - reddit
        - search_count
        - sentiment
        - slug
        - smart_contract
        - status_tags
        - tags
        - telegram
        - total_employees
        - total_valuation
        - trajectory
        - twitter
        - updated_at
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
        - youtube
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - audit_file
        - blockchain_network
        - careers_page
        - coin_id
        - company_linkedin
        - date_added
        - external_id
        - github
        - ico_end
        - ico_start
        - id
        - investor_amount
        - layer
        - layer_detail
        - logo
        - market_verified
        - name
        - notes
        - overview
        - slug
        - smart_contract
        - tags
        - total_employees
        - total_valuation
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
      filter: {}
      limit: 50
      allow_aggregations: true
  - role: viewer
    permission:
      columns:
        - aliases
        - audit_file
        - bitcointalk
        - blockchain_explorer
        - blockchain_network
        - careers_page
        - coin_id
        - company_linkedin
        - created_at
        - datapoints_count
        - date_added
        - discord
        - facebook
        - geopoint
        - github
        - glassdoor
        - ico_end
        - ico_start
        - id
        - instagram
        - investor_amount
        - layer
        - layer_detail
        - library
        - location
        - location_json
        - logo
        - market_verified
        - medium
        - name
        - notes
        - num_of_views
        - overview
        - reddit
        - search_count
        - sentiment
        - slug
        - smart_contract
        - status
        - status_tags
        - tags
        - telegram
        - total_employees
        - total_valuation
        - trajectory
        - twitter
        - updated_at
        - velocity_linkedin
        - velocity_token
        - website
        - white_paper
        - year_founded
        - youtube
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
