table:
  name: events
  schema: public
object_relationships:
  - name: parent_event
    using:
      manual_configuration:
        column_mapping:
          parent_event_id: id
        insertion_order: null
        remote_table:
          name: events
          schema: public
array_relationships:
  - name: event_organization
    using:
      manual_configuration:
        column_mapping:
          id: event_id
        insertion_order: null
        remote_table:
          name: event_organization
          schema: public
  - name: event_person
    using:
      manual_configuration:
        column_mapping:
          id: event_id
        insertion_order: null
        remote_table:
          name: event_person
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - attachments
        - banner
        - created_at
        - discord
        - end_date
        - end_time
        - facebook
        - geopoint
        - id
        - instagram
        - is_featured
        - library
        - link
        - location_json
        - name
        - notes
        - overview
        - parent_event_id
        - price
        - size
        - slug
        - start_date
        - start_time
        - status
        - telegram
        - timezone
        - twitter
        - types
        - updated_at
        - venue_name
      filter:
        status:
          _eq: published
      limit: 50
      allow_aggregations: true
