table:
  schema: public
  name: notes
object_relationships:
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - created_by
        - id
        - resource_id
        - user_group_id
        - notes
        - resource_type
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
