table:
  schema: public
  name: user_group_members
object_relationships:
  - name: user
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users_public
        insertion_order: null
        column_mapping:
          user_id: id
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - user_group_id
        - user_id
      filter:
        _or:
          - user_group:
              public:
                _eq: true
          - user_group:
              user_group_members:
                user_id:
                  _eq: X-Hasura-User-Id
      limit: 50
