table:
  schema: public
  name: notification_actions
object_relationships:
  - name: action
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: actions
        insertion_order: null
        column_mapping:
          action_id: id
  - name: notification
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: notifications
        insertion_order: null
        column_mapping:
          notification_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - action_id
        - id
        - notification_id
        - created_at
      filter: {}
      allow_aggregations: true
