table:
  schema: public
  name: news
array_relationships:
  - name: organizations
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: news_organizations
        insertion_order: null
        column_mapping:
          id: news_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - created_at
        - updated_at
        - date
        - text
        - link
        - status
      filter:
        status:
          _eq: published
      limit: 50
