table:
  schema: public
  name: event_person
object_relationships:
  - name: event
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: events
        insertion_order: null
        column_mapping:
          event_id: id
  - name: person
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: people
        insertion_order: null
        column_mapping:
          person_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - event_id
        - id
        - person_id
        - type
        - created_at
      filter: {}
