table:
  schema: public
  name: investment_rounds
object_relationships:
  - name: company
    using:
      foreign_key_constraint_on: company_id
array_relationships:
  - name: investments
    using:
      foreign_key_constraint_on:
        column: round_id
        table:
          schema: public
          name: investments
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - company_id
        - id
        - amount
        - valuation
        - external_id
        - round
        - round_date
      backend_only: false
select_permissions:
  - role: api_viewer
    permission:
      columns:
        - amount
        - company_id
        - currency
        - external_id
        - id
        - round
        - round_date
        - valuation
      filter:
        status:
          _eq: published
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - company_id
        - id
        - amount
        - valuation
        - external_id
        - round
        - round_date
      filter: {}
  - role: viewer
    permission:
      columns:
        - amount
        - company_id
        - currency
        - external_id
        - id
        - round
        - round_date
        - valuation
      filter:
        status:
          _eq: published
      allow_aggregations: true
