table:
  schema: public
  name: news_person
object_relationships:
  - name: news
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: news
        insertion_order: null
        column_mapping:
          news_id: id
  - name: people
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: people
        insertion_order: null
        column_mapping:
          person_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - is_author
        - id
        - news_id
        - person_id
        - created_at
        - updated_at
      filter: {}
      limit: 50
