table:
  schema: public
  name: list_members
object_relationships:
  - name: user
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          user_id: id
