table:
  schema: public
  name: user_group_members
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
  - name: user_group
    using:
      foreign_key_constraint_on: user_group_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - id
        - user_group_id
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      limit: 50
      allow_aggregations: true
