table:
  schema: public
  name: resource_links
object_relationships:
  - name: from_company
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: companies
        insertion_order: null
        column_mapping:
          from_company_id: id
  - name: from_vc_firm
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: vc_firms
        insertion_order: null
        column_mapping:
          from_vc_firm_id: id
  - name: to_company
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: companies
        insertion_order: null
        column_mapping:
          to_company_id: id
  - name: to_vc_firm
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: vc_firms
        insertion_order: null
        column_mapping:
          to_vc_firm_id: id
select_permissions:
  - role: viewer
    permission:
      columns:
        - from_company_id
        - from_vc_firm_id
        - to_company_id
        - to_vc_firm_id
        - link_type
        - id
      filter: {}
      limit: 50
