table:
  schema: public
  name: billing_org
object_relationships:
  - name: billing_org_id
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: users
        insertion_order: null
        column_mapping:
          id: billing_org_id
select_permissions:
  - role: viewer
    permission:
      columns:
        - customer_id
        - id
        - plan
        - status
        - user_limit
      filter:
        billing_org_id:
          id:
            _eq: X-Hasura-User-Id
      allow_aggregations: true
