table:
  name: billing_org
  schema: public
object_relationships:
  - name: users
    using:
      manual_configuration:
        column_mapping:
          id: billing_org_id
        insertion_order: null
        remote_table:
          name: users
          schema: public
select_permissions:
  - role: viewer
    permission:
      columns:
        - customer_id
        - id
        - plan
        - status
        - user_limit
      filter:
        users:
          id:
            _eq: X-Hasura-User-Id
