name: apply hasura and update data_fields
on:
  push:
    branches: 
      - main

env:
  HASURA_ENDPOINT: https://graphql.edgein.dev
  HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}

jobs:
  apply-hasura-update-data_fields:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Hasura migrate
        uses: tibotiber/hasura-action@v3.0
        with:
          args: migrate apply --database-name default
        env:
          HASURA_WORKDIR: ./infra/hasura
          HASURA_ENGINE_VERSION: v2.29.1
          HASURA_ENDPOINT: ${{ env.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ env.HASURA_ADMIN_SECRET }}

      - name: Hasura clear
        uses: tibotiber/hasura-action@v3.0
        with:
          args: metadata clear
        env:
          HASURA_WORKDIR: ./infra/hasura
          HASURA_ENGINE_VERSION: v2.29.1
          HASURA_ENDPOINT: ${{ env.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ env.HASURA_ADMIN_SECRET }}

      - name: Hasura apply
        uses: tibotiber/hasura-action@v3.0
        with:
          args: metadata apply
        env:
          HASURA_WORKDIR: ./infra/hasura
          HASURA_ENGINE_VERSION: v2.29.1
          HASURA_ENDPOINT: ${{ env.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ env.HASURA_ADMIN_SECRET }}

      - name: Update data fields
        working-directory: ./scripts
        shell: bash
        run: npx ts-node update_data_fields.ts