name: Deploy to preview environment
on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to deploy'
        required: true
        default: preview

env:
  PROJECT_NAME: edgein

jobs:
  sha:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - name: Set SHA
        run: echo SHA=${{ steps.short-sha.outputs.sha }} >> $GITHUB_ENV

  setup:
    uses: 5of5/edgein-next/.github/actions/setup.yml@improve/641-staging-env
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ vars.AWS_REGION }}
      vercel-commit: ${{ env.SHA }}
      vercel-team: ${{ secrets.VERCEL_TEAM }}
      vercel-api-token: ${{ secrets.VERCEL_API_TOKEN }}

  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Set workspace
        run: |
          if [[ "${{ github.event.inputs.workspace }}" == "preview" ]]; then
            echo WORKSPACE=pr-${{ github.event.pull_request.number }} >> $GITHUB_ENV
          else
            echo WORKSPACE=${{ github.event.inputs.workspace }} >> $GITHUB_ENV
          fi

      - name: Terraform Validate
        id: validate
        working-directory: infra/terraform/application
        run: terraform validate -no-color

      - name: Terraform select workspace
        id: select-workspace
        working-directory: infra/terraform/application
        run: terraform workspace select -or-create ${{ env.WORKSPACE }}
        
      - name: Create preview environment
        working-directory: infra/terraform/application
        run: terraform apply --auto-approve -var-file="input.tfvars"

  hasura:
    uses: 5of5/edgein-next/.github/actions/hasura.yml@improve/641-staging-env