name: Check eslint and prettier
on:
  pull_request:
    branches:
      - main
jobs:
  eslint-and-prettier:
    name: Check eslint and prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier-check