name: Remove preview environment
on:
  pull_request:
    branches:
      - stage
    types:
      - closed
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to deploy'
        required: true
        default: preview

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: ${{vars.AWS_REGION}}
  PROJECT_NAME: edgein

jobs:
  remove:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Setup steps
        uses: 5of5/edgein-next/.github/actions/setup.yml@${{ github.ref }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          vercel-commit: ${{ GITHUB_SHA::8 }}
          vercel-team: ${{ secrets.VERCEL_TEAM }}
          vercel-api-token: ${{ secrets.VERCEL_API_TOKEN }}

      - name: Set workspace
        run: |
          if [[ "${{ github.event.inputs.workspace }}" == "preview" ]]; then
            echo WORKSPACE=pr-${{ github.event.pull_request.number }} >> $GITHUB_ENV
          else
            echo WORKSPACE=${{ github.event.inputs.workspace }} >> $GITHUB_ENV
          fi

      - name: Terraform select workspace
        id: select-workspace
        working-directory: infra/terraform/application
        run: terraform workspace select ${{ env.WORKSPACE }}

      - name: Destroy preview environment
        working-directory: infra/terraform/application
        run: terraform destroy --auto-approve -var-file="input.tfvars"

      - name: Remove workspace
        id: remove-workspace
        working-directory: infrastructure/application
        run: terraform workspace delete ${{ env.WORKSPACE }}