-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO public.data_fields ("name", "path", resource, weight) VALUES
--     ('source', 'news.source', 'news', 1),
--     ('created_at', 'news.created_at', 'news', 1),
--     ('is_publisher', 'news_organizations.is_publisher', 'news_organizations', 1);
